### ISSUE TITLE
side effects of a given module can be set by app author

### ISSUE THREAD

**Issue by kzc** [filipesilva/webpack-rxjs-operators#1]
@filipesilva Don't know if you're aware of this, but in webpack 4 an app author can deem any given module to be side effect free from their webpack config:

https://github.com/webpack/webpack/pull/6129/files#diff-b968d7026d16261e6e3fddfa5a949155R8

**Comment by filipesilva** [comment]
I did not know this, no! Sweet.

**Comment by kzc** [comment]
Cool.

**Comment by filipesilva** [comment]
Just pushed a commit that makes use of it https://github.com/filipesilva/webpack-rxjs-operators/commit/ca4b3d8f705a948fa6cd9dfd7b44711a45ab0179

**Comment by kzc** [comment]
Nice.

I'm not sure it's a documented option in the webpack next branch. The PR had a TODO related to that.

**Comment by filipesilva** [comment]
There's a mentioned https://github.com/webpack/webpack/issues/6132, there's one of these issues for each alpha now.
